### ISSUE TITLE
jquery as a dependency should be lowercase in bower.json

### ISSUE THREAD

**Issue by jmallison** [Mediafly/mflyCommands#6]
One more tweak to make for bower.json.

All projects specified as dependencies should be in lowercase. Currently the dependency for jquery is like this:

>  "dependencies": {
>    "jQuery": "~1.11.0"
>  }

This causes issues during bower updates. Please change it to this:

>  "dependencies": {
>    "jquery": "~1.11.0"
>  }

**Comment by nmehta6** [comment]
Fixed. Thanks.

**Comment by jmallison** [comment]
Thanks, can you put up a tag with that change?

**Comment by nmehta6** [comment]
Just pushed tag v1.9.9.
